# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
# https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: tcp-json-pipeline
  path.config: "/usr/share/logstash/pipeline/tcp-json-pipeline.conf"
  pipeline.workers: 1

- pipeline.id: tcp-filebeat-pipeline
  path.config: "/usr/share/logstash/pipeline/tcp-filebeat-pipeline.conf"
  pipeline.workers: 1
