version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    env_file:
      - ./kibana.env
    ports:
      - 5601:5601
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        labels: "kibana,elk"
