version: '3'
services:
  nginx:
    build: .
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/apache2:/etc/apache2
    ports:
      - 80:80
      - 5959:5959
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        labels: "nginx"
