version: '3'
services:
  logstash1:
    image: docker.elastic.co/logstash/logstash:6.3.0
    volumes:
      - ./config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./config/pipeline:/usr/share/logstash/pipeline
      - ./volumes/data1:/usr/share/logstash/data
    env_file:
      - ./logstash.env
    environment:
      node.name: logstash-1
    ports:
      - 9601:9600
      - 5961:5959
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        labels: "logstash,elk"

  logstash2:
    image: docker.elastic.co/logstash/logstash:6.3.0
    volumes:
      - ./config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./config/pipeline:/usr/share/logstash/pipeline
      - ./volumes/data2:/usr/share/logstash/data
    env_file:
      - ./logstash.env
    environment:
      node.name: logstash-2
    ports:
      - 9602:9600
      - 5962:5959
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        labels: "logstash,elk"
